// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewsSite;

namespace ReviewsSite.Migrations
{
    [DbContext(typeof(BevContext))]
    partial class BevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewsSite.Models.Bev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bevs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Soda",
                            Description = "A sweetened, carbonated soft drink flavored with vanilla, cinnamon, citrus oils and other flavorings. Most contain caffeine, which was originally sourced from the kola nut, leading to the drink's name, though other sources are now also used. Cola became popular worldwide after pharmacist John Pemberton invented Coca-Cola in 1886, which was later imitated by other manufacturers.His non-alcoholic recipe was inspired by the coca wine of pharmacist Angelo Mariani, created in 1863.",
                            Image = "Images/coke.jpg",
                            Name = "Coke",
                            Review = " 10/10 Would recommend."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Soda",
                            Description = "Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad's Drink, it was renamed as Pepsi-Cola in 1898, and then shortened to Pepsi in 1961.",
                            Image = "Images/Pepsipic.jpg",
                            Name = "Pepsi",
                            Review = "Disappointing."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Energy Drink",
                            Description = "Red Bull is an energy drink sold by Red Bull GmbH, an Austrian company created in 1987. Red Bull has the highest market share of any energy drink in the world, with 7.5 billion cans sold in a year (as of 2019).",
                            Image = "Images/RedBull.jpg",
                            Name = "Red Bull",
                            Review = "Yummy"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Energy Drink",
                            Description = "Monster Energy is an energy drink that was introduced by Hansen Natural Company in April of 2002. As of 2019, Monster Energy has a 35% share of the energy drink market, the second highest share after Red Bull.",
                            Image = "Images/Monster.jpg",
                            Name = "Monster",
                            Review = "It's mediocre"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sparkling Water",
                            Description = "LaCroix or La Croix is an American brand of carbonated water that originated in La Crosse, Wisconsin by G. Heileman Brewing Company and is now distributed by National Beverage Corporation.",
                            Image = "Images/LaCroix.jpg",
                            Name = "La Croix",
                            Review = "Refreshlingy bubbly"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sparkling Water",
                            Description = "America's first sparkling water made with just real squeezed fruit.",
                            Image = "Images/Spindrift.jpg",
                            Name = "SpinDrift",
                            Review = "It's like La Croix's cooler sibling"
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BevId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BevId");

                    b.ToTable("ReviewList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BevId = 1,
                            Content = "Too carbonated.",
                            Rating = 5,
                            ReviewDate = new DateTime(2021, 3, 5, 11, 27, 28, 953, DateTimeKind.Local).AddTicks(1939),
                            ReviewerName = "Carlos"
                        },
                        new
                        {
                            Id = 2,
                            BevId = 2,
                            Content = "Offensive to the pallete",
                            Rating = 0,
                            ReviewDate = new DateTime(2021, 3, 5, 11, 27, 28, 959, DateTimeKind.Local).AddTicks(4572),
                            ReviewerName = "Davis"
                        });
                });

            modelBuilder.Entity("ReviewsSite.Models.Review", b =>
                {
                    b.HasOne("ReviewsSite.Models.Bev", "Bev")
                        .WithMany("Reviews")
                        .HasForeignKey("BevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bev");
                });

            modelBuilder.Entity("ReviewsSite.Models.Bev", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
